pred:
	time python LOO_DataAnalysis.py
	time python createLOO.py

perf:
	time python st_DataAnalysis.py
	time python createST.py
	#time python pred_st.py

data:
	time python createData.py
	mv ../parser/*.csv ../ndat/
